datasources:
  h2:
    url: jdbc:h2:mem:public;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver

kestra:
  queue:
    type: h2
  repository:
    type: h2
  storage:
    type: local
    local:
      basePath: /tmp/
  tasks:
    tmpDir:
      path: /tmp
